In [1]:
import pandas as pd

In [2]:
# Utility function to return a "cleaned school" name.
def clean_school_name(s):
    
    arr = s.split()
    
    # If the last word is 'School', drop it.
    if arr[len(arr)-1].lower() == 'school':
        arr.pop()
        
    # Convert all words to lowercase.
    for i in range(0, len(arr)):
        arr[i] = arr[i].lower()
        
    return ' '.join(arr)

In [11]:
# Load the school ratings data.
schools_df = pd.read_csv('mcps_school_ratings.csv')
schools_df.head()

,School,Address,Rating,Type,Enrollment,Students per Teacher,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Burning Tree Elementary,"7900 Beech Tree Road, Bethesda, MD, 20817",10.0,E,473,13.0,NaN,NaN,NaN,NaN
1,Spark M. Matsunaga Elementary School,"13902 Bromfield Road, Germantown, MD, 20874",9.0,E,728,17.0,NaN,NaN,NaN,NaN
2,Bannockburn Elementary,"6520 Dalroy Lane, Bethesda, MD, 20817",9.0,E,440,17.0,NaN,NaN,NaN,NaN
3,Bells Mill Elementary,"8225 Bells Mill Road, Potomac, MD, 20854",9.0,E,619,16.0,NaN,NaN,NaN,NaN
4,Cold Spring Elementary,"9201 Falls Chapel Way, Potomac, MD, 20854",9.0,E,330,16.0,NaN,NaN,NaN,NaN

In [14]:
# Iterate over all schools.
for index, row in schools_df.iterrows():
    
    clean_sn = clean_school_name(row['School'])
    schools_df.loc[index, 'School'] = clean_sn
    
schools_df = schools_df.filter(items=['School', 'Address', 'Rating', 'Type', 'Enrollment', 'Students per Teacher'],
                              axis=1)

schools_df

,School,Address,Rating,Type,Enrollment,Students per Teacher
0,burning tree elementary,"7900 Beech Tree Road, Bethesda, MD, 20817",10.0,E,473,13.0
1,spark m. matsunaga elementary,"13902 Bromfield Road, Germantown, MD, 20874",9.0,E,728,17.0
2,bannockburn elementary,"6520 Dalroy Lane, Bethesda, MD, 20817",9.0,E,440,17.0
3,bells mill elementary,"8225 Bells Mill Road, Potomac, MD, 20854",9.0,E,619,16.0
4,cold spring elementary,"9201 Falls Chapel Way, Potomac, MD, 20854",9.0,E,330,16.0
...,...,...,...,...,...,...
194,watkins mill high,"10301 Apple Ridge Road, Gaithersburg, MD, 20886",4.0,H,1615,14.0
195,northwood high,"919 University Boulevard West, Silver Spring, ...",3.0,H,1732,14.0
196,gaithersburg high,"101 Education Boulevard, Gaithersburg, MD, 20877",3.0,H,2352,13.0
197,john f. kennedy high,"1901 Randolph Road, Silver Spring, MD, 20902",3.0,H,1781,14.0
198,seneca valley high,"19401 Crystal Rock Drive, Germantown, MD, 20874",3.0,H,1181,13.0

In [15]:
schools_df.to_csv('mcps_school_ratings_clean.csv')